UPDATE task SET task_name = 'niet_onderwijsTaak1' WHERE task_name= 'java programming';
UPDATE task SET task_name = 'niet_onderwijsTaak2' WHERE task_name= 'C++ programming';
UPDATE task SET task_name = 'niet_onderwijsTaak3' WHERE task_name= 'AI analyse';
UPDATE task SET task_name = 'niet_onderwijsTaak4' WHERE task_name= 'Stage begeleiding';
UPDATE task SET task_name = 'niet_onderwijsTaak5' WHERE task_name= 'MIW project ondersteuning';
UPDATE task SET task_name = 'niet_onderwijsTaak6' WHERE task_name= 'OOP advanced';
UPDATE task SET task_name = 'niet_onderwijsTaak7' WHERE task_name= 'C++ problems and solutions';
UPDATE task SET task_name = 'niet_onderwijsTaak8' WHERE task_name= 'Googlen voor studenten';
UPDATE task SET task_name = 'niet_onderwijsTaak9' WHERE task_name= 'pascal';
UPDATE task SET task_name = 'niet_onderwijsTaak10' WHERE task_name= 'Fourier analyse module1';


INSERT INTO task (task_id,estimated_hours,task_name,years_to_expiry_date) VALUES (11,31,'niet_onderwijstaak11',3);
INSERT INTO task (task_id,estimated_hours,task_name,years_to_expiry_date) VALUES (12,32,'niet_onderwijstaak12',3);
INSERT INTO task (task_id,estimated_hours,task_name,years_to_expiry_date) VALUES (13,30,'niet_onderwijstaak13',3);
INSERT INTO task (task_id,estimated_hours,task_name,years_to_expiry_date) VALUES (14,13,'niet_onderwijstaak14',3);
INSERT INTO task (task_id,estimated_hours,task_name,years_to_expiry_date) VALUES (15,23,'niet_onderwijstaak15',3);
INSERT INTO task (task_id,estimated_hours,task_name,years_to_expiry_date) VALUES (16,43,'niet_onderwijstaak16',3);
INSERT INTO task (task_id,estimated_hours,task_name,years_to_expiry_date) VALUES (17,6,'niet_onderwijstaak17',3);
INSERT INTO task (task_id,estimated_hours,task_name,years_to_expiry_date) VALUES (18,12,'niet_onderwijstaak18',3);
INSERT INTO task (task_id,estimated_hours,task_name,years_to_expiry_date) VALUES (19,9,'niet_onderwijstaak19',3);
INSERT INTO task (task_id,estimated_hours,task_name,years_to_expiry_date) VALUES (20,10,'niet_onderwijstaak20',3);
INSERT INTO task (task_id,estimated_hours,task_name,years_to_expiry_date) VALUES (21,11,'niet_onderwijstaak21',3);
INSERT INTO task (task_id,estimated_hours,task_name,years_to_expiry_date) VALUES (22,13,'niet_onderwijstaak22',3);
INSERT INTO task (task_id,estimated_hours,task_name,years_to_expiry_date) VALUES (23,15,'niet_onderwijstaak23',3);
INSERT INTO task (task_id,estimated_hours,task_name,years_to_expiry_date) VALUES (24,17,'niet_onderwijstaak24',3);
INSERT INTO task (task_id,estimated_hours,task_name,years_to_expiry_date) VALUES (25,19,'niet_onderwijstaak25',3);
INSERT INTO task (task_id,estimated_hours,task_name,years_to_expiry_date) VALUES (26,21,'niet_onderwijstaak26',3);
INSERT INTO task (task_id,estimated_hours,task_name,years_to_expiry_date) VALUES (27,23,'niet_onderwijstaak27',3);
INSERT INTO task (task_id,estimated_hours,task_name,years_to_expiry_date) VALUES (28,25,'niet_onderwijstaak28',3);