INSERT INTO Task (task_Id,task_Name,estimated_Hours,years_To_Expiry_Date) VALUES (1,'java programming',32,3);
INSERT INTO Task (task_Id,task_Name,estimated_Hours,years_To_Expiry_Date) VALUES (2,'C++ programming',16,3);
INSERT INTO Task (task_Id,task_Name,estimated_Hours,years_To_Expiry_Date) VALUES (3,'AI analyse',8,3);
INSERT INTO Task (task_Id,task_Name,estimated_Hours,years_To_Expiry_Date) VALUES (4,'Stage begeleiding',24,3);
INSERT INTO Task (task_Id,task_Name,estimated_Hours,years_To_Expiry_Date) VALUES (5,'MIW project ondersteuning',200,3);
INSERT INTO Task (task_Id,task_Name,estimated_Hours,years_To_Expiry_Date) VALUES (6,'OOP advanced',32,3);
INSERT INTO Task (task_Id,task_Name,estimated_Hours,years_To_Expiry_Date) VALUES (7,'C++ problems and solutions',16,3);
INSERT INTO Task (task_Id,task_Name,estimated_Hours,years_To_Expiry_Date) VALUES (8,'Googlen voor studenten',16,3);
INSERT INTO Task (task_Id,task_Name,estimated_Hours,years_To_Expiry_Date) VALUES (9,'pascal',16,3);
INSERT INTO Task (task_Id,task_Name,estimated_Hours,years_To_Expiry_Date) VALUES (10,'Fourier analyse module1',16,3);
